// Utility for exporting analysis to different formats

import { Analysis } from '@/lib/types';
import { format } from 'date-fns';
import { enUS } from 'date-fns/locale';

/**
 * Generates a text format report
 */
export function generateTextReport(analysis: Analysis): string {
  const date = format(new Date(analysis.timestamp), 'MM/dd/yyyy HH:mm', { locale: enUS });

  return `
╔════════════════════════════════════════════════════════════════╗
║             TECHNICAL ANALYSIS - TRADING AI                     ║
╚════════════════════════════════════════════════════════════════╝

Asset: ${analysis.symbol}
Timeframe: ${analysis.timeframe.toUpperCase()}
Date: ${date}

────────────────────────────────────────────────────────────────

TREND: ${analysis.trend.toUpperCase()}
Confidence: ${analysis.confidence}%

────────────────────────────────────────────────────────────────

ANALYSIS:
${analysis.analysis}

────────────────────────────────────────────────────────────────

RECOMMENDATION:
${analysis.recommendation}

────────────────────────────────────────────────────────────────

TECHNICAL LEVELS:
Support: $${analysis.support.toFixed(2)}
Resistance: $${analysis.resistance.toFixed(2)}

────────────────────────────────────────────────────────────────

Generated by TradingIA - AI-Powered Analysis
`;
}

/**
 * Generates a CSV format report
 */
export function generateCSVReport(analyses: Analysis[]): string {
  const headers = ['Asset', 'Timeframe', 'Date', 'Trend', 'Confidence', 'Support', 'Resistance'];
  const rows = analyses.map((a) => [
    a.symbol,
    a.timeframe,
    format(new Date(a.timestamp), 'MM/dd/yyyy HH:mm'),
    a.trend,
    a.confidence,
    a.support,
    a.resistance,
  ]);

  const csv = [headers, ...rows].map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n');
  return csv;
}

/**
 * Generates a JSON format report
 */
export function generateJSONReport(analyses: Analysis[]): string {
  return JSON.stringify(analyses, null, 2);
}

/**
 * Exports data to a file
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const element = document.createElement('a');
  element.setAttribute('href', `data:${mimeType};charset=utf-8,${encodeURIComponent(content)}`);
  element.setAttribute('download', filename);
  element.style.display = 'none';

  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

/**
 * Exports analysis as text file
 */
export function exportAnalysisAsText(analysis: Analysis) {
  const content = generateTextReport(analysis);
  const filename = `analysis_${analysis.symbol}_${format(new Date(), 'MM-dd-yyyy-HHmm')}.txt`;
  downloadFile(content, filename);
}

/**
 * Exports multiple analyses as CSV
 */
export function exportAnalysisAsCSV(analyses: Analysis[]) {
  const content = generateCSVReport(analyses);
  const filename = `analysis_${format(new Date(), 'MM-dd-yyyy-HHmm')}.csv`;
  downloadFile(content, filename, 'text/csv');
}

/**
 * Exports analysis as JSON
 */
export function exportAnalysisAsJSON(analyses: Analysis[]) {
  const content = generateJSONReport(analyses);
  const filename = `analysis_${format(new Date(), 'MM-dd-yyyy-HHmm')}.json`;
  downloadFile(content, filename, 'application/json');
}

/**
 * Captures a chart as an image
 */
export async function captureChartAsImage(elementId: string, filename: string) {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error(`Element with ID ${elementId} not found`);
    }

    // html2canvas or similar would be used in a real implementation
    console.log(`Capturing chart: ${elementId}`);
  } catch (error) {
    console.error('Error capturing chart:', error);
    throw error;
  }
}

/**
 * Prints the analysis
 */
export function printAnalysis(analysis: Analysis) {
  const content = generateTextReport(analysis);
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    // SAFE: Use textContent instead of document.write
    printWindow.document.body.style.fontFamily = 'monospace';
    printWindow.document.body.style.whiteSpace = 'pre-wrap';
    // Create pre element and use textContent (no HTML injection)
    const pre = printWindow.document.createElement('pre');
    pre.textContent = content;
    pre.style.margin = '20px';
    printWindow.document.body.appendChild(pre);
    printWindow.document.close();
    printWindow.print();
  }
}

/**
 * Copies analysis to clipboard
 */
export async function copyAnalysisToClipboard(analysis: Analysis) {
  const content = generateTextReport(analysis);
  try {
    await navigator.clipboard.writeText(content);
    return true;
  } catch (error) {
    console.error('Error copying to clipboard:', error);
    return false;
  }
}

